### ISSUE TITLE
Negative latency when curcuit breaker is in open state

### ISSUE THREAD

**Issue by yoorick** [ahus1/prometheus-hystrix#12]
I noticed that sometimes counters for `_hystrix_command_latency_execute_seconds_sum` and `_hystrix_command_latency_total_seconds_sum` have small glitches like that:

```
8891.582999999922 @1509010418.551
8891.617999999922 @1509010419.551
8891.633999999922 @1509010420.551
8891.633999999922 @1509010421.551 <-- attention
8891.631999999921 @1509010422.551 <-- attention
8891.631999999921 @1509010423.551
8891.64699999992 @1509010424.551
8891.68199999992 @1509010425.551
```
Prometheus' functions like `rate()` or `increase()` tend to think that there is a reboot between these two values and produce a huuuuge peak on the graph.

Deeper investigation showed that this is because of a series of short-circuited executions. The value for latency in case of short-circuit is always -1 ms.
The debug code like that:
```
HystrixCommandCompletionStream.getInstance(cmdKey)
    .observe()
    .subscribe(hystrixCommandCompletion -> {
        LOG.warn(
            "CMD Completion: executed={} {}",
            hystrixCommandCompletion.didCommandExecute(),
            hystrixCommandCompletion.toString(),
        );
    });
```
produces:
```
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=true listItemsByUserId[FAILURE][2 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=true listItemsByUserId[FAILURE][2 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
CMD Completion: executed=false listItemsByUserId[SHORT_CIRCUITED][-1 ms]
```

In purely synthetical tests with 100% failure rate the total sum of latency can even go below 0:
```
hystrix_command_latency_execute_seconds_count{command_group="SOME_GROUP",command_name="listItemsByUserId",} 684.0
hystrix_command_latency_execute_seconds_sum{command_group="SOME_GROUP",command_name="listItemsByUserId",} -0.3050000000000003
hystrix_command_latency_total_seconds_count{command_group="SOME_GROUP",command_name="listItemsByUserId",} 684.0
hystrix_command_latency_total_seconds_sum{command_group="SOME_GROUP",command_name="listItemsByUserId",} -0.21800000000000028
```
(Time machine, isn't it? :) )

I think that this could be safely fixed by this additional check in `HystrixPrometheusMetricsPublisherCommand` class:
```
HystrixCommandCompletionStream.getInstance(commandKey)
    .observe()
    .subscribe(hystrixCommandCompletion -> {
        if (hystrixCommandCompletion.didCommandExecute()) {
            histogramLatencyTotal.observe(hystrixCommandCompletion.getTotalLatency() / 1000d);
            histogramLatencyExecute.observe(hystrixCommandCompletion.getExecutionLatency() / 1000d);
        }
        for (HystrixEventType hystrixEventType : HystrixEventType.values()) {
            // this code is not touched
        }
    });
```

What do you think?

**Comment by ahus1** [comment]
Well spottet! I agree, this should fix it and would be the most semantic code to write (didCommandExecute). 

On the other hand I would think I would rather add a "... >= 0" instead. This would also catch situations where clocks were running backwards (could happen to adjust clock skew). 

Do you want to provide a pull request? I'd be happy to release a new version early next week. 

Regards,
Alexander

**Comment by ahus1** [comment]
... or we should have the logic you describe AND an additional check not to add any negative durations (just in case and for time skews... and maybe log).

**Comment by yoorick** [comment]
Here's my pull request -- https://github.com/ahus1/prometheus-hystrix/pull/13
But it doesn't contain additional check for clock running backwards. Should I extend it?

**Comment by ahus1** [comment]
I've merged your changes and added some more tests. 

I found that there are different situations where _didCommandExecute()_ returns false and some or all latencies are set to proper values. Please see the test cases for timed out and cancelled commands. 

Therefore I decided to check _latency >= 0_ before updating the histogram. 

This still makes your test case pass. I also added a check for clock skew (_latency_ less than _-1_). It's now quite tricky to find out what events will update the histogram and what won't, but I assume that's how Hystrix works. I search for some documentation online but didn't find it.

Please have a look. A snapshot version is available from the snapshot repository at Sonatype. 

If this works for you, I'll release a new version.

**Comment by yoorick** [comment]
Thanks for thorough verification!
I've tested the new snapshot version with our application locally, looks good to me.

One minor note, if you don't mind, according code uniformity, you tried to avoid using getter multiple times in case of totalLatency, but not in case of executionLatency:
```
histogramLatencyTotal.observe(totalLatency / 1000d);
...
histogramLatencyExecute.observe(hystrixCommandCompletion.getExecutionLatency() / 1000d);
```

**Comment by ahus1** [comment]
Thanks for the review of my changes. I fixed that. I triggered a release and it should be available on maven central shortly.
