### ISSUE TITLE
java 7 compatibility

### ISSUE THREAD

**Issue by stoneliyi** [ahus1/prometheus-hystrix#16]
Hi, I am trying to use this cool lib in my application for publishing hystrix metrics. unfortunately, the application fails to start up. I figure that it's because that the application is on java 7 while this lib requires 1.8. 

we don't have a plan to upgrade to java 8. and I found that all versions in maven central are 3.x which requires java 8.

So my question is what's the best way to get it work on java 7? as we just need basic functionalities, I am thinking to re-build 2.x with java 7. Is that the way to go? Can you confirm? 

Thanks!

**Comment by ahus1** [comment]
Tom did a really go migration to JDK8. But I see that Hystrix and Prometheus both still support JDK6. 

I used the IDE to make the code compile and run on JDK6+ -- it adds quite a lot of code, but I think this is the way to go as both support JDK6. But I still felt a bit bad to do this... 

I pushed some changes (actually quite some changes). A new snapshot release is now available in the snapshot repository as 3.3.2-SNAPSHOT. 

Please give it a try and tell me if how this works for you.

**Comment by stoneliyi** [comment]
Hi @ahus1, thanks a lot for your quick response and changes. really appreciated! I am trying it now and will let you know if it works.

**Comment by stoneliyi** [comment]
Hi @ahus1, i have given 3.3.2-SNAPSHOT a try. it works fine with java 7. Awesome! 

for now, we can just use 3.3.2-SNAPSHOT with snapshot repository. is there any plan to make 3.3.2 or new versions java 6 or 7 compatible and publish to maven central?

**Comment by ahus1** [comment]
I'll release a version 3.4.0 to maven central that include this "feature". I plan to add some more build automation first. Expect it some time next week.

JDK6/JDK7 will stay with this library as long as Prometheus Java Client and Hystrix also stay on JDK6/JDK7. Once one of them changes, this library will change as well.

**Comment by stoneliyi** [comment]
@ahus1 thanks. it makes sense to make it jdk6/jdk7 compatible as long as its dependencies Prometheus and Hystrix are jdk6/jdk7 compatible. 

will check out 3.4.0 next week!

**Comment by ahus1** [comment]
This has been released as version 3.4.0 and should be available on Maven Central soon. I added another code change to have the labels in the same order in both JDK7 and JDK8 - please re-test when using the released version.
