### ISSUE TITLE
Fixed / global labels

### ISSUE THREAD

**Issue by naude-r** [ahus1/prometheus-hystrix#17]
We would like to add a fixed label to each metric, e.g. service_name="MyService". This is needed to be able to distinguish between different service instances. In our cases the hystrix command key / group is the same as it is physically the same code, just different named instances.

Using the namespace is not really an option as this make finding & using metrics more difficult.

Ideally one should be able to provide a factory of some kind to create e.g. a counter / histogram. We can then provide a subclass of the real prometheus metric and add our logic as required.

Any other thoughts?

**Comment by naude-r** [comment]
If can work if we could sub-class HystrixMetricsCollector and override addGauge and friends to add a new label / value. Unfortunately there is no way to supply a HystrixMetricsCollector instance to HystrixPrometheusMetricsPublisher either...

**Comment by naude-r** [comment]
This issue can be closed. The advise from the prometheus guys (and rightly so) is to rather add global labels during scraping time.

See also [issue 330](https://github.com/prometheus/client_java/issues/330)

Feel free to ignore PR #18

**Comment by ahus1** [comment]
Thanks for sharing this information here. I close the PR.
