### ISSUE TITLE
Update <artifactId>simpleclient</artifactId> to 0.4.0

### ISSUE THREAD

**Issue by Abyss89** [ahus1/prometheus-hystrix#21]
If update the simpclient to
<dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient</artifactId>
            <version>0.4.0</version>
</dependency>

prometheus-hystrix will be work?

**Comment by ahus1** [comment]
I've given it a try locally with 0.4.0 and 0.6.0 - all tests are green, so this should be fine. As usual you should test in your environment as well. 

As you can update the version of simpleclient in your local build file I will not release a new version of this library.
