### ISSUE TITLE
prometheus-hystrix not working with micrometer.io libraries

### ISSUE THREAD

**Issue by fdimauro** [ahus1/prometheus-hystrix#24]
This no longer works. It appears that micrometer.io has replaced it. I have:
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>de.ahus1.prometheus.hystrix</groupId>
            <artifactId>prometheus-hystrix</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>

But never do I see a hystrix_command_event_total, after many calls to apis have been made, in the output of /actuator/prometheus. I see a lot of micrometer output but nothing from prometheus-hystrix.

Does you library no longer work now that we have micrometer.io?

**Comment by ahus1** [comment]
If you want to see this libraries version of the metrics, you probably want to disable micrometers metrics on Hystrix.

You can do this with a configuration option management.metrics.binders.hystrix.enabled like I did in the following configuration:

https://github.com/ahus1/prometheusspringbootminimal/blob/master/src/main/resources/application.properties#L14

Please note that this is the spring boot 2.x name of the option. Earlier I think it was called 
 management.metrics.export.hystrix.enabled

I can dig deeper into this once you name the versions you use, but only in the week after next week.

**Comment by ahus1** [comment]
This ticket has been open for quite some time. If you're using Micrometer, IMHO you should use Micrometer to report Hystrix metrics. Still if you prefer, you can use both reportings.
