### ISSUE TITLE
Creating Dashboard for mean Latency

### ISSUE THREAD

**Issue by HendrikBoerste** [ahus1/prometheus-hystrix#26]
Hi everyone,

I am currently trying to create a Grafana Dashbooard with some of the Hystrix Prometheus metrics. One of them is a Graf that should show the mean latency over time. 
Therefore I am using the following query:
`avg(hystrix_command_latency_total_seconds_sum{command_group=~"$commandGroup", command_name=~"$commandName"} ) by (command_name, command_group)`

Unfortunately it feels like the used metric just sums up all latencies over time, because my graph looks like this:
![image](https://user-images.githubusercontent.com/34372108/69943068-57b88c00-14e5-11ea-971e-f5556437ac4c.png)

I tried to divide the metric `hystrix_command_latency_total_seconds_sum` by `hystrix_command_latency_total_seconds_count`, but this gives me very unrealistic low results.

Does anyone know how to properly create a query for a mean latency over time?

Thanks in advance!

**Comment by ahus1** [comment]
Both metrics are always increasing, meaning the sum up the time and the counts from the start of the application. You already described this in your question. 

To calculate a moving average of the request time, you'll first need to apply [`rate(metric{...}[5m])`](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) first. Then calculate the ratio. In the example above this would look like this: 

```
rate(hystrix_command_latency_total_seconds_sum[5m])
/
rate(hystrix_command_latency_total_seconds_count[5m])
```

When you later want to sum up metrics from several instanaces, first use rate() on your metrics, then sum(). [See this excellent post "Rate then sum, never sum then rate" by one of the maintainers for details](https://www.robustperception.io/rate-then-sum-never-sum-then-rate).

Please be aware that averages can be misleading, percentiles and histograms give you more insight on what's happening in your system. prometheus-hystrix already provides histograms. Read more about histograms in the blog post [How does a Prometheus Histogram work?](https://www.robustperception.io/how-does-a-prometheus-histogram-work),

**Comment by HendrikBoerste** [comment]
@ahus1 That was exactly what I am looking for, thank you very much!
And thanks as well for the articles, the histograms look really helpful.
