### ISSUE TITLE
Remove some of hystrix metrics

### ISSUE THREAD

**Issue by rchumarin** [ahus1/prometheus-hystrix#45]
Is it possible to remove some of metrics from REST endpoint (e.g. remove everything except "hystrix_command_event_total") ?
but cannot find a way to filter collectors that I don't need.

**Comment by ahus1** [comment]
The library doesn't offer that feature. I suggest to use the Prometheus scrape config for that; there you can use relabeling and the action "drop" to ignore metrics by wildcard.

See https://prometheus.io/docs/prometheus/latest/configuration/configuration/ for more information.
