### ISSUE TITLE
Another strategy was already registered.

### ISSUE THREAD

**Issue by pradyb** [ahus1/prometheus-hystrix#5]
Hi,

I'm using Spring Cloud Sleuth to track the calls. So, Sleuth registers the default MetricsPublisher. 
When HystrixPrometheusMetricsPublisher is tries to register with HystrixPlugins throws "Another strategy was already registered." error.

**Comment by beorn7** [comment]
If this is still an issue, please follow up in the https://github.com/ahus1/prometheus-hystrix repo (which is the maintained fork of this repo).

**Comment by ahus1** [comment]
New maintainer on board, and the repo has been moved. No need to open a new ticket. 
I know about this problem and have a working solution in mind.

**Comment by pradyb** [comment]
Thanks @ahus1

**Comment by ahus1** [comment]
I wrote a test case to reproduce the error and adopted the same strategy Sleuth applies: to wrap any existing provider. 

Please give it a try and provide feedback. Maybe you also want to look into #4 as it will be part of the next release.

To try it out you can use the 3.2.0-SNAPSHOT release available from Sonartype OSS repo (more on that on the main README.adoc in the repo).

**Comment by ahus1** [comment]
This has now been released as 3.2.0 on maven central.

**Comment by pradyb** [comment]
Thanks @ahus1 for fixing this issue. The code looks fine and working without any issue.

On the another note, is someone updating the Grafana Dashboard based on the new changes
[Grafana Hystrix Dashboard](https://grafana.com/dashboards/2113)

**Comment by ahus1** [comment]
@pradyb - good to hear that it is working for you. 

I wasn't aware of this dashboard. For now the old metrics should work as before.

Maybe @sergiu-svinarciuc can help here? As he has uploaded it, he has the permissions to update it.
